# Generated by Django 6.1 on 2026-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_alter_payment_options_remove_payment_mpesa_receipt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
