# Generated by Django 6.1 on 2026-08-27 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('breed', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('age', models.FloatField()),
                ('age_unit', models.CharField(default='years', max_length=20)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('verified', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('health_certified', models.BooleanField(default=False)),
                ('farmer_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
