# Generated by Django 6.1 on 2026-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
