# Generated by Django 6.1 on 2026-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("no_payment", "No Payment"),
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("payment_failed", "Payment Failed"),
                ],
                default="no_payment",
                max_length=20,
            ),
        ),
    ]
