# Generated by Django 6.1 on 2026-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_idempotency_key_order_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("timeout", "Timeout"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
